<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMaui>true</UseMaui>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.41" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\EncryptionClasses\ArgonParameters.cs" Link="ArgonParameters.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\EncryptionClasses\OSTypes.cs" Link="OSTypes.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\EncryptionClasses\IEncryptionFunctions.cs" Link="IEncryptionFunctions.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\EncryptionClasses\EncryptionFunctions.cs" Link="EncryptionFunctions.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\FileInputOutputClasses\FileWorker.cs" Link="FileWorker.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\FileInputOutputClasses\keyManager.cs" Link="keyManager.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\Backend(Art)\Data\IHasID.cs" Link="IHasID.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\Backend(Art)\Data\PasswordEntry.cs" Link="PasswordEntry.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\FileInputOutputClasses\SecureRepository.cs" Link="SecureRepository.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\SecurityServices\ISecureClipboardService.cs" Link="ISecureClipboardService.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\SecurityServices\SecureClipboardService.cs" Link="SecureClipboardService.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\NetworkProtocols\PairingSecret.cs" Link="PairingSecret.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\NetworkProtocols\P2PProtocol.cs" Link="P2PProtocol.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\sql(rus)\FileInputOutputClasses\VaultImportTransaction.cs" Link="VaultImportTransaction.cs" />
    <Compile Include="..\SecurePassword\SecurePassword\VaultSessionService.cs" Link="VaultSessionService.cs" />
  </ItemGroup>

</Project>
